### ISSUE TITLE
How To Make Flappy?

### ISSUE THREAD

**Issue by Agrda215** [Throngjwk/folders#7]
# How to making flappy?
### **Can Be TO HTML5 DOCTYPE**:
```html
<!DOCTYPE html>
```
#4 - and be now stuffed to flappy in issues.
### Make Flappys
You Where needed to `<html lang="en">` be end at `</html>`.
### Head Tips
Need:
```html
<h1 class="score" id="score" style="text-align:center;">0</h1>
<canvas class="flappy" width="480" height="360"></canvas>
```
### Be Out
@Throngjwk - Make Flappy get be pull request.
### CSS
```css
h1.score {
  color:darkblue;
}

body {
  background-color:rgba(10, 255, 10, 0.7);
  font-family:sans-serif;
}
```

**Comment by Agrda215** [comment]
# BODY and HEAD
```html
<head></head>
<body></body>
```

**Comment by Throngjwk** [comment]
Need to center canvas!

**Comment by Agrda215** [comment]
> Need to center canvas!

```html
<div class="tabs">
  <canvas class="flappy" width="480" height="360"></canvas>
</div>
```
```css
div.tabs {
   display:flex;
   justify-content:center;
}
```

**Comment by Agrda215** [comment]
### You Need
```css
canvas.flappy {
   background-color:orange;
}
```
