### ISSUE TITLE
With Be Colors

### ISSUE THREAD

**Issue by Throngjwk** [Throngjwk/folders#9]
### WITHOUT GRAPH
`Cool` out!

### LINK
[Without Graph](https://www.desmos.com/calculator/97plwx44xk)

**Comment by Agrda215** [comment]
With with?
```txt
a=\operatorname{hsv}\left(\pi+\frac{b}{2}+\left(b_{1}+b_{4}+\left(d_{1}-b_{7}-b_{9}\right)+b_{8}+\cos\left(\sqrt{\frac{b_{1}}{\sqrt{2}}}\right)\cdot\cos\left(\sqrt{2}\right)+\left(\sqrt{b_{2}}-\left(1+\cos\left(b_{3}\right)\right)\right)+\max\left(2\cdot b_{5},\ b_{2}\cdot\cos\left(80+b_{6}\right)\right)\right),\ 0.5+c,\ 0.9\right)
```

**Comment by Agrda215** [comment]
[Colored](https://www.desmos.com/calculator/td5aniqwu3)

**Comment by Agrda215** [comment]
> [Colored](https://www.desmos.com/calculator/td5aniqwu3)

```txt
C=\operatorname{rgb}\left(a^{3}+\frac{b_{11}}{\sqrt{10+\ln\left(b_{56}\right)}}+b_{21}+\left(b_{22}+b_{41}\cdot\pi\right)+b_{28}+\ln\left(b_{38}\right)+\ln\left(b_{53}\right)+b_{43},\sqrt{b_{17}}+b_{1}+\left(b_{2}\cdot\cos\left(\frac{b_{17}}{2}\right)\right)+\frac{b_{30}}{2},\left(1-b_{3}\right)+b_{4}+\frac{b_{5}}{\frac{\tau}{3}}+b_{11}+\frac{e^{3}}{u\cdot3}+\log_{2}\left(80\cdot\left(\frac{\pi}{\frac{a}{3-\left(\frac{b_{24}}{10-b_{55}}\right)}}\right)\right)\cdot b_{6}+\frac{b_{7}}{5}+\log_{3}\left(b_{8}\cdot b_{9}\cdot b_{10}\cdot b_{11}\cdot b_{12}\cdot b_{13}\cdot b_{14}\cdot b_{15}\cdot b_{16}\right)+b_{18}+\left(b_{20}^{2}\cdot\tau\right)+\log_{40}\left(b_{21}\cdot b_{22}\cdot b_{25}^{2}\ \cdot\ b_{26}\right)+b_{27}+\frac{b_{29}}{15}+\log_{1.15}\left(b_{31}\cdot b_{32}^{\sqrt{\frac{2}{b_{51}}}}\cdot b_{33}\right)+\ln\left(b_{34}\cdot b_{35}\cdot2^{b_{36}}\cdot b_{37}\cdot\left(b_{40}\cdot20^{5}\right)\cdot\left(b_{41}\cdot m_{1}\right)\right)+\left(b_{39}-1\right)+\ln\left(b_{44}\cdot b_{45}\right)+\left(2-b_{46}\right)+b_{47}+\log_{9}\left(b_{48}\cdot b_{49}\cdot b_{50}\cdot\frac{10^{7}}{\ln\left(b_{52}\right)}\right)\cdot\left(\log_{10}\left(\log_{10}\left(b_{54}\right)\right)+1\right)+\frac{b_{57}}{\log_{9}\left(2048\right)}+\left(b_{58}+b_{59}^{2}\right)+\ln\left(10^{b_{60}}\right)+\log_{9}\left(b_{61}\right)+\ln\left(b_{62}\cdot b_{63}\cdot b_{64}^{2}\cdot W\left(120,\ 3,\ 6,\ 2\right)\right)+\log_{6}\left(b_{65}\cdot W\left(3,\ 6,\ 3,\ 6\right)\cdot W\left(6,\ 12,\ 6,\ 12\right)\cdot W\left(12,\ 24,\ 12,\ 24\right)\right)+\sqrt{\max\left(0,\ b_{66}\cdot\ln\left(b_{67}\cdot b_{68}\cdot b_{69}^{2}\cdot b_{70}^{\sqrt{2}}\right)\right)}+\sqrt{\ln\left(b_{71}\cdot b_{72}^{\sqrt{3}}\cdot b_{73}^{2}\cdot b_{74}^{b_{1}}\right)}+\sqrt{b_{75}\cdot\ln\left(W\left(20,\ 20,\ 20,\ 4\right)\cdot W\left(20,\ 40,\ 60,\ 2\right)\cdot W\left(20,\ 30,\ 40,\ 3\right)\cdot W\left(2,4,6,8\right)\right)}+\log_{100}\left(b_{76}\cdot b_{77}\right)+\sqrt{b_{78}+\ln\left(b_{79}\cdot b_{80}^{\sqrt{2}}\cdot b_{81}\cdot b_{82}^{2}\right)+\log_{2}\left(b_{83}\right)}+b_{84}+\log_{10}\left(b_{85}\cdot b_{86}\right)+\sqrt{b_{87}+\ln\left(b_{88}\cdot b_{89}\right)}+\log_{10}\left(b_{90}\cdot W\left(3,\ 2,\ 3,\ 2\right)\ \cdot\ W\left(2,\ 3,\ 4,\ 5\right)\ \cdot\ W\left(3,3,3,3\right)\ \cdot\ W\left(10,\ 10,\ 10,\ 10\right)\ \cdot\ W\left(7,\ 2,\ 3,\ 7\right)\cdot b_{91}\cdot b_{92}\right)+\sqrt{b_{93}+\ln\left(b_{94}\cdot b_{95}\cdot b_{96}^{\sqrt{2}}\cdot b_{97}^{2}\cdot b_{98}^{\sqrt{2}}\cdot b_{99}^{\sqrt{3}}\right)}+\log_{2}\left(b_{100}\cdot W\left(42,\ 62,\ 82,\ 102\right)\cdot b_{101}\cdot b_{102}\cdot\left(b_{103}-1\right)\cdot b_{104}\right)+\log_{6}\left(b_{105}^{\frac{2}{\frac{\pi}{2}}}\right)+\sqrt{\sqrt{b_{106}+\ln\left(b_{107}\cdot b_{108}\cdot b_{109}\cdot\frac{b_{110}}{3}\cdot\frac{b_{111}}{4}^{\sqrt{2}}\cdot b_{112}\cdot b_{113}\cdot b_{114}^{\sqrt{2}}\cdot\frac{b_{115}}{10^{3}}\cdot b_{116}\cdot\sqrt{b_{117}+\ln\left(b_{118}\cdot\frac{b_{119}}{\sqrt{2}}\cdot\frac{b_{120}^{2}}{69420}\cdot b_{121}^{2}\cdot b_{122}^{\sqrt{\frac{\pi}{2}}}\cdot b_{123}\cdot b_{124}^{2}\cdot\sqrt{b_{125}^{3}}\cdot b_{126}\cdot b_{127}^{2}\cdot\sqrt{b_{128}^{\sqrt{2}}\cdot\cos\left(0.8\right)}\cdot b_{129}\cdot b_{130}^{0.4}\right)}\right)}}+\ln\left(W\left(22,\ 33,\ 44,\ 55\right)\cdot W\left(9,\ 9,\ 9,\ 9\right)\cdot b_{131}\cdot\frac{b_{132}}{10}\cdot b_{133}^{\sqrt{2}}\cdot\frac{b_{134}}{6}\cdot b_{135}\right)\right)
```

**Comment by TheCreator2022** [comment]
> [Colored](https://www.desmos.com/calculator/td5aniqwu3)

![Colored](https://raw.githubusercontent.com/TheCreator2022/folders/patch-1/image%20issues/Screenshots_2022-08-09-13-58-57.png)

**Comment by TheCreator2022** [comment]
https://www.desmos.com/calculator/xm0ygknyug?lang=pt-BR

**Comment by Agrda215** [comment]
https://www.desmos.com/calculator/fjqijy4rhx?lang=pt-BR

**Comment by Agrda215** [comment]
Vue logo created based desmos!
https://www.desmos.com/calculator/wocu1vmrdf

**Comment by Agrda215** [comment]
Be Out!

**Comment by Agrda215** [comment]
# Can be use of be!
```css
text-shadow: 28px 28px 2px #0806CE, 27px 27px 5px rgba(8,99,206,0.99), 26px 26px 5px rgba(23,137,206,0.98), 25px 25px 5px rgba(35,108,206,0.97), 24px 24px 6px rgba(62,118,206,0.97), 23px 23px 5px rgba(31,53,206,0.97), 22px 22px 6px rgba(23,143,206,0.96), 21px 21px 6px #15CEC3, 20px 20px 5px #16DBD0, 19px 19px 6px #11A69E, 18px 18px 6px #17E8C0, 17px 17px 7px rgba(30,232,200,0.98), 16px 16px 6px #19E8B9, 15px 15px 5px #3CE8B6, 14px 14px 6px rgba(37,232,156,0.99), 13px 13px 6px #2AE832, 12px 12px 7px #46E827, 11px 11px 6px #87E81C, 10px 10px 5px rgba(168,232,23,0.99), 9px 9px 6px #D1E815, 8px 8px 6px #E7E82E, 7px 7px 5px #E8BF33, 6px 6px 5px #B07228, 5px 5px 5px #C27E2C, 4px 4px 6px #E67B3C, 3px 3px 6px #AD432D, 2px 2px 5px #E38632, 1px 1px 5px #D1AF1D, 0px 0px 5px #BD7015, -1px -1px 5px #998E1C, -2px -2px 5px #BBD132, -3px -3px 5px #A6D134, -3px -3px 6px #71D12A, -1px -2px 6px #41D132, 1px 1px 8px #82D12A, 3px 0px 8px #ACD11F, 3px 6px 9px #7FD151, 8px 5px 8px rgba(187,209,81,0.97), 15px 1px 7px #D19C49, 9px -3px 7px #41D1B5, 13px 5px 7px #6ED14B, 29px 29px 7px #6A34D1, 30px 30px 6px #A730D1, 27px 27px 11px #56D18C, 25px 25px 12px #80B53E, 20px 22px 12px #2AB56C, 17px 17px 11px #2DDCE3, 14px 8px 11px #17E35C, 13px 11px 10px #C4E330, 10px 7px 10px #3DBBDB, 7px 19px 9px #593DDB, 13px 17px 9px #318B9E, 19px 11px 9px #478525, 23px 4px 9px #4DDBC5, 17px 13px 8px #62BD42, 28px 8px 9px #3371B0, 23px 11px 9px #2FB042, 20px 7px 9px #6909B0, 15px 17px 9px #CA4895, 9px 14px 9px rgba(202,72,149,0.98), 26px 8px 7px rgba(172,48,202,0.98), 20px 5px 9px rgba(73,128,202,0.97), 17px 20px 9px rgba(75,91,202,0.97), 25px 20px 9px rgba(67,181,110,0.97), 22px 12px 10px #3F56B5, 17px 29px 10px #9948B5, 17px 29px 10px #9948B5;
```

**Comment by Agrda215** [comment]
https://admitted-picayune-bearskin.glitch.me

**Comment by Throngjwk** [comment]
https://sly-oxidized-catamaran.glitch.me/

**Comment by Agrda215** [comment]
Get Example Maintisa Popanka Shadow:
```js
.my-over {
    display: flex;
    align-items: center;
    justify-content: center;
    line-height: 1;
    color: #000000;
    font-size: 50px;
    text-shadow: 2px 2px 3px rgba(5, 203, 250, 1), 3px 3px 3px rgba(64, 176, 191, 1), 4px 4px 3px rgba(60, 187, 204, 1), 5px 5px 3px rgba(51, 191, 210, 1), 6px 6px 3px rgba(36, 187, 207, 1), 7px 7px 3px rgba(33, 163, 180, 1), 8px 8px 3px rgba(68, 127, 197, 1), 9px 9px 3px rgba(7, 98, 206, 1), 10px 10px 3px rgba(4, 64, 231, 1), 11px 11px 3px rgba(30, 48, 225, 1), 12px 12px 3px rgba(21, 40, 229, 1), 13px 13px 3px rgba(18, 33, 182, 1), 14px 14px 3px rgba(92, 59, 140, 1), 15px 15px 3px rgba(113, 63, 186, 1), 16px 16px 3px rgba(126, 69, 207, 1), 17px 17px 3px rgba(119, 44, 226, 1), 18px 18px 3px rgba(85, 17, 182, 1), 19px 19px 3px rgba(125, 42, 167, 1), 20px 20px 3px rgba(125, 13, 181, 1), 21px 21px 3px rgba(133, 11, 163, 1), 22px 22px 3px rgba(161, 14, 197, 1), 23px 23px 3px rgba(215, 21, 210, 1), 24px 24px 3px rgba(183, 18, 132, 1), 25px 25px 3px rgba(221, 15, 157, 1), 26px 26px 3px rgba(172, 122, 104, 1), 27px 27px 3px rgba(189, 134, 113, 1), 28px 28px 3px rgba(203, 129, 101, 1), 29px 29px 3px rgba(214, 83, 34, 1), 30px 30px 3px rgba(235, 111, 19, 1), 31px 31px 3px rgba(200, 151, 13, 1), 32px 32px 3px rgba(195, 151, 26, 1), 33px 33px 3px rgba(234, 214, 20, 1), 34px 34px 3px rgba(197, 206, 19, 1), 35px 35px 3px rgba(184, 210, 45, 1), 36px 36px 3px rgba(156, 231, 21, 1), 37px 37px 3px rgba(138, 207, 14, 1), 38px 38px 3px rgba(125, 228, 19, 1), 39px 39px 3px rgba(125, 228, 19, 1), 40px 40px 3px rgba(105, 207, 80, 1), 41px 41px 3px rgba(98, 221, 68, 1), 42px 42px 3px rgba(91, 221, 60, 1), 43px 43px 3px rgba(51, 201, 55, 1), 44px 44px 3px rgba(44, 219, 112, 1), 45px 45px 3px rgba(103, 172, 149, 1), 46px 46px 3px rgba(71, 225, 173, 1), 47px 47px 3px rgba(75, 210, 215, 1), 48px 48px 3px rgba(52, 201, 207, 1), 49px 49px 3px rgba(39, 154, 223, 1), 50px 50px 3px rgba(55, 113, 211, 1), 51px 51px 3px rgba(82, 123, 193, 1), 52px 52px 3px rgba(56, 103, 183, 1), 53px 53px 3px rgba(50, 114, 223, 1), 54px 54px 3px rgba(54, 75, 170, 1), 55px 55px 3px rgba(50, 78, 206, 1), 56px 56px 3px rgba(109, 95, 203, 1), 57px 57px 3px rgba(95, 77, 217, 1), 58px 58px 3px rgba(90, 30, 213, 1), 59px 59px 3px rgba(90, 30, 213, 1), 60px 60px 3px rgba(174, 46, 200, 1), 61px 61px 3px rgba(192, 40, 223, 1), 62px 62px 3px rgba(214, 69, 211, 1), 63px 63px 3px rgba(227, 51, 223, 1), 64px 64px 3px rgba(208, 62, 184, 1), 65px 65px 3px rgba(214, 41, 132, 1), 66px 66px 3px rgba(155, 53, 103, 1), 67px 67px 3px rgba(201, 151, 113, 1), 68px 68px 3px rgba(203, 146, 103, 1), 69px 69px 3px rgba(183, 125, 81, 1), 70px 70px 3px rgba(225, 136, 68, 1), 71px 71px 3px rgba(225, 157, 68, 1), 72px 72px 3px rgba(217, 146, 53, 1), 73px 73px 3px rgba(219, 137, 30, 1), 74px 74px 3px rgba(182, 127, 23, 1), 75px 75px 3px rgba(183, 148, 37, 1), 76px 76px 3px rgba(202, 186, 37, 1), 77px 77px 3px rgba(217, 199, 28, 1), 78px 78px 3px rgba(169, 203, 89, 1), 79px 79px 3px rgba(167, 205, 79, 1), 80px 80px 3px rgba(136, 205, 74, 1);
    font-weight: bold;
  }
```

**Comment by Agrda215** [comment]
# HOW?
I guy example:
```css
background: linear-gradient(45deg, hsla(265, 31%, 39%, 1) 0%, hsla(274, 57%, 44%, 1) 8%, hsla(285, 41%, 45%, 1) 15%, hsla(234, 50%, 35%, 1) 23%, hsla(331, 79%, 28%, 1) 37%, hsla(343, 67%, 43%, 1) 44%, hsla(165, 56%, 39%, 1) 50%, hsla(161, 54%, 45%, 1) 56%, hsla(156, 57%, 50%, 1) 62%, hsla(178, 59%, 30%, 1) 69%, hsla(125, 32%, 42%, 1) 76%, hsla(109, 27%, 49%, 1) 85%, hsla(47, 93%, 73%, 1) 100%);
```

**Comment by Agrda215** [comment]
Can be:
```css
.original-box-shadow {
  display: flex;
  align-items: center;
  justify-content: center;
  color: #333333;
  background-color: #dddddd;
  font-size: 30px;
  width: 300px;
  height: 110px;
  border-radius: 11px;
  box-shadow: 3px 3px 6px 0px rgba(203, 145, 35, 1), 4px 4px 6px 0px rgba(217, 170, 82, 1), 5px 5px 6px 0px rgba(170, 161, 36, 1), inset 6px 6px 6px 0px rgba(202, 196, 111, 1), inset 7px 7px 6px 0px rgba(189, 181, 67, 1), inset 8px 8px 6px 0px rgba(189, 181, 67, 1), inset 9px 9px 6px 0px rgba(238, 227, 69, 1), inset 10px 10px 6px 0px rgba(101, 110, 22, 1), inset 11px 11px 6px 0px rgba(148, 203, 18, 1), inset 12px 12px 6px 0px rgba(196, 229, 48, 1), inset 13px 13px 6px 0px rgba(153, 214, 42, 1), inset 14px 14px 6px 0px rgba(155, 228, 50, 1), inset 15px 15px 6px 0px rgba(134, 191, 52, 1), inset 16px 16px 6px 0px rgba(82, 119, 28, 1), inset 17px 17px 6px 0px rgba(81, 121, 24, 1), inset 18px 18px 6px 0px rgba(154, 201, 87, 1), inset 19px 19px 6px 0px rgba(155, 246, 24, 1), inset 20px 20px 6px 0px rgba(100, 221, 31, 1), inset 21px 21px 6px 0px rgba(48, 223, 25, 1), inset 22px 22px 6px 0px rgba(89, 210, 19, 1), inset 23px 23px 6px 0px rgba(71, 199, 28, 1), inset 24px 24px 6px 0px rgba(108, 180, 66, 1), inset 25px 25px 6px 0px rgba(131, 200, 91, 1), inset 26px 26px 6px 0px rgba(89, 210, 19, 1), inset 27px 27px 6px 0px rgba(89, 210, 19, 1), inset 28px 22px 6px 0px rgba(95, 186, 36, 1), inset 29px 29px 6px 0px rgba(193, 235, 168, 1), inset 30px 30px 6px 0px rgba(50, 119, 10, 1), inset 31px 31px 6px 0px rgba(136, 202, 98, 1), inset 32px 32px 6px 0px rgba(89, 210, 19, 1), inset 32px 32px 6px 0px rgba(88, 218, 110, 1), inset 34px 34px 6px 0px rgba(75, 176, 75, 1), inset 35px 35px 6px 0px rgba(139, 189, 109, 1), inset 36px 36px 6px 0px rgba(79, 167, 53, 1), inset -2px -2px 6px 0px rgba(64, 181, 29, 1), inset -3px -3px 6px 0px rgba(152, 236, 127, 1), inset -4px -4px 6px 0px rgba(115, 192, 92, 1), inset -5px -5px 6px 0px rgba(82, 208, 45, 1), inset -6px -6px 6px 0px rgba(108, 215, 77, 1), inset -7px -7px 6px 0px rgba(152, 236, 127, 1), inset -8px -8px 6px 0px rgba(69, 123, 53, 1), inset -9px -9px 6px 0px rgba(79, 208, 111, 1), inset -10px -10px 6px 0px rgba(101, 204, 71, 1);
}
```
